### ISSUE TITLE
Instructions outdated

### ISSUE THREAD

**Issue by kumavis** [NHQ/jsynth#2]
followed the instructions with a fresh clone and had a few problems.
global opa doesnt end up in my path somehow, no problem ill use a local one.
not serving bundle.js? hmm ill mess with the args a bit. Now bundle.js is an html file hmm...
ihavenoideawhatimdoing.jpg
ihavenoattentionspan.gif
solongandthanksforallthefish.tiff

**Comment by NHQ** [comment]
probably

**Comment by NHQ** [comment]
opa docs out of date.  now it passes all args to browserify so
```
opa entry.js -o public/bundle.js
```
except 
```
opa -c newProjectFolder
```
which creates a template project

**Comment by NHQ** [comment]
If you post the jsynth example into [requirebin](http://requirebin.com/?gist=139605e821da088f51a7) it works.
or into [node.module.club](http://node.module.club), and hit SHIFT-ENTER

**Comment by NHQ** [comment]
oops opa needs "-i" so make that:
```js
opa -i entry.js -o bundle.js
```

**Comment by NHQ** [comment]
opa needs -e

```js
opa -e entry.js -o bundle.js
```

like old browserify

**Comment by kumavis** [comment]
nice, thanks
